@startuml
'https://plantuml.com/class-diagram

interface IRepository<t> {
    +Task<List<T>> GetAllAsync()
    +Task<T> GetByIdAsync(int id)
    +Task<T> AddAsync(T entity)
    +Task<T> UpdateAsync(T entity)
    +Task<T> DeleteAsync(T entity)
}


interface IUnitOfWork {
    +IRepository<User> Users
    +IRepository<TodoItem> TodoItems
    +IRepository<TodoList> TodoLists
    +IRepository<Project> Projects
    +IRepository<Label> Labels
    +IRepository<Role> Roles
    +IRepository<Permission> permissions
    +IRepository<UserProjectRole> UserProjectRoles
    +Task SaveChangesAsync()
}

IUnitOfWork -- IRepository : contains

@enduml